on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build packages
        # Github CI has a limit of 256 jobs per matrix, so we just try to build everything at once.
        run: |
          currentSystem="$(nix eval --raw --impure --expr builtins.currentSystem)"
          nix run github:Mic92/nix-fast-build -- \
            --eval-workers 1 \
            --no-nom \
            --skip-cached \
            --flake .#lib.$currentSystem.packagesValid
